Blog post: Import Path FAQ
ethereum/solidity-blog pull request #147
Opened 2021-08-16 12:56 UTC by cameel

This is still work in progress, but I'm submitting it already to get some early feedback. I have the later sections sketched out but I still need to turn my outline into nice text and add examples.

It's pretty long, though given how much I had to cut from the path docs, this is to be expected. I wonder if should maybe split it into smaller posts though?

2021-08-17 10:15 UTC, chriseth commented on _posts/2021-08-16-import-path-faq.md
> +Even when using [Standard JSON](https://docs.soliditylang.org/en/latest/using-the-compiler.html#compiler-input-and-output-json-description) format, allows tools to access that structure directly, the
grammar is off

2021-08-18 10:45 UTC, cameel commented
I have just pushed the remaining text. The post is now complete but I want to make another pass through it before I mark it as ready for review. I know there are some typos and grammar errors and it needs some polishing. Especially in the later sections where I focused on finally getting it all out with the intention of fixing small details later.

The feedback that would be most useful at this point is whether the overall structure makes sense. Looking at section titles and just lightly skimming through text and examples - does it look ok? I decided to use the FAQ format in the hope of making it more interesting and addressing real problems I've seen rather than just throwing a long monotonous list of examples at the reader, but the downside of this approach is that I ended up re-explaining some stuff that's already in the docs.

2021-08-19 12:52 UTC, franzihei commented
My two gwei to the current state:
- Overall structure seems fine
- The post is __really__ long. Not many people will read such a long post. If it is not possible to explain the stuff shorter that's ok I guess, but it usually helps to offer different levels of details aka, have a digest of what is important to know somewhere in the beginning (like a tl;dr) and then the more detailed stuff
- The title doesn't necessarily motivate to read more / is not really intriguing.. maybe we can tweak it a bit?

2021-08-19 15:22 UTC, cameel commented
Yeah, I'm fully aware that it's way too long for its own good, just I'm not sure how it can serve its purpose without that level of detail. Part of the reason path handling is notoriously buggy and inconsistent, is that no one really wants to dig that deep into all these details and special cases. There's tons of them and it's very tedious. Laying them out like this makes it easier than having to figure them out on your own. Though it definitely won't beat the ease of not having to worry about them :)

I'm going to try to make it more concise, which should help a bit but that probably won't be more than 10-20% without cutting stuff. The problem really is that the post is all detail :) It's not meant to give a high level overview because that's what the docs I wrote earlier already do. Maybe I should just assume that the reader has fully read the docs? That would let me omit some explanations but it would also make it hard to read the post on its own.

Maybe the best solution would be to split it into two parts? I wanted to avoid it because I don't think the topic is interesting enough to people that they'd want to read multiple articles about it, but two parts is not that much and maybe preferable to having one monster article anyway :) I think I could fairly cleanly split it into one post focusing on compiler's VFS and another dealing only with the import callback and the actual filesystem.

> The title doesn't necessarily motivate to read more / is not really intriguing.. maybe we can tweak it a bit?

True, the title is a bit plain. Here's some more ideas:
- "Dealing with import problems in Solidity"
- "Common problems with import paths"
- "Deep dive into compiler's virtual filesystem"
- "Imports and the filesystem"
- "The import callback and the VFS"
- "More than you ever wanted to know about import paths in Solidity"
- "The twisted paths of Solidity" (a really bad pun :P)

Also maybe you have some ideas yourself?

2022-07-04 15:15 UTC, Marenz requested changes

2022-07-04 15:15 UTC, Marenz commented on _posts/2021-08-16-import-path-faq.md
> +In the end the source code in most cases comes from a filesystem and users do not refer to it using abstract identifiers.
```suggestion
In the end the source code comes in most cases from a filesystem and users don't refer to it using abstract identifiers.
```

2022-07-04 15:15 UTC, Marenz commented on _posts/2021-08-16-import-path-faq.md
> +Even when using [Standard JSON](https://docs.soliditylang.org/en/latest/using-the-compiler.html#compiler-input-and-output-json-description) format, allows tools to access that structure directly, the
```suggestion
And while our [Standard JSON](https://docs.soliditylang.org/en/latest/using-the-compiler.html#compiler-input-and-output-json-description) format allows tools to access that structure directly, the burden just shifts to the tool.
```

2022-07-04 15:15 UTC, Marenz commented on _posts/2021-08-16-import-path-faq.md
> +The details of the whole mechanism have recently been documented in [Import Path Resolution](https://docs.soliditylang.org/en/latest/path-resolution.html) but many of the consequences of the document
```suggestion
The details of the whole mechanism have recently been added to our [Import Path Resolution documentation](https://docs.soliditylang.org/en/latest/path-resolution.html) but many of the consequences of the documented behavior may not be apparent.
```

2022-07-04 15:15 UTC, Marenz commented on _posts/2021-08-16-import-path-faq.md
> +### Q: What's wrong with relative paths in Solidity? Aren't `import "file.sol"` and `import "./file.sol"` the same thing?
```suggestion
### Q: What's wrong with relative paths in Solidity? Isn't `import "file.sol"` the same as `import "./file.sol"`?
```

Yours is grammatically correct as well. Dunno I felt mine reads nicer, but just a suggestion.

2022-07-04 15:15 UTC, Marenz commented on _posts/2021-08-16-import-path-faq.md
> +`file.sol` is actually considered absolute in compiler's virtual filesystem.
```suggestion
`file.sol` is actually considered absolute in the compiler's virtual filesystem.
```

2022-12-05 18:47 UTC, closed without merging